/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle */
using namespace cv;
#ifndef _Included_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle
#define _Included_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle
#ifdef __cplusplus
extern "C" {
#endif

void detect_face(Mat& frame);

JNIEXPORT void JNICALL Java_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle_faceDetection
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
