/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle */

#ifndef _Included_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle
#define _Included_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle_faceDetection
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
