/* DO NOT EDIT THIS FILE - it is machine generated */
#include "medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle.h"
/* Header for class medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle */

JNIEXPORT void JNICALL Java_medialib_reactive_trach_com_opencvfacedetector_OpenCVMiddle_faceDetection
  (JNIEnv *, jobject, jlong addrRgba){

}


